Build update
enonic/site-developer pull request #365
Opened 2021-05-03 11:34 UTC by poi33

Fix for: 
#303 
#147 
#125 

Where the removal of gulp is the biggest changes. 303

2021-05-03 12:07 UTC, ComLock commented on build.gradle
> +				//'**/*.html',
?

2021-05-03 12:11 UTC, ComLock requested changes

2021-05-03 12:11 UTC, ComLock commented on build.gradle
> +				//'**/*.html',
If webpack handles html, then gradle shouldn't, or order of gradle tasks could mean no html minification

2021-05-03 12:15 UTC, poi33 commented on build.gradle
> +				//'**/*.html',
Legger den til igjen. Var kode fra før minify html fungerte.

2021-05-07 07:31 UTC, ComLock approved these changes

2021-05-10 11:45 UTC, merged