Add feedback form
enonic/site-developer pull request #408
Opened 2021-06-16 13:36 UTC by thomasheartman

This PR adds a feedback form to the bottom of reference docs and guides as requested in #328.

[... more to come as the PR evolves.]

2021-06-16 13:42 UTC, thomasheartman commented
# Current status:

This is what it looks like on the page:
![image](https://user-images.githubusercontent.com/17786332/122229113-c2a79900-ceb8-11eb-8a8e-6ebf4e2a0c1f.png)

and this is what the GitHub issue contains by default:

![image](https://user-images.githubusercontent.com/17786332/122229445-09958e80-ceb9-11eb-86b0-781313847fe3.png)


## On the code

Because I'm not familiar with the system, I've taken the easy way out and simply added the new code within the same function that I was working on. This is possibly not ideal and maybe it should be moved. What are the standards for this? 

## Further work:

I'd like to do what both Microsoft and Mozilla do and add some visual distinction to the feedback section; either via a background color or via some sort of border. However, I'd need to look for defined color variables etc first.

If we are to add a standard HTML form to make submission easier, then I suggest we create a separate issue/PR for that.

2021-06-17 06:37 UTC, sigdestad commented
Definetly need to make this look different from the doc. Now it looks like a part of the document

2021-06-17 08:34 UTC, poi33 requested changes
Could you add a black border ontop of the feedback <article> ? 
Probably need to move it outside of <div class="docpage-content"> for this to look proper. 
Add the styling to src\main\resources\assets\css\parts\_docpage.scss Make a new scss file, our _docpage is way to big already.

2021-06-17 08:34 UTC, poi33 commented on src/main/resources/site/parts/docpage/docpage.html
> +		<article>
The document uses spaces, as fasr as i cant tell. Could you keep use 4 spaces instead of tabs? There should be an option for the editor to add 4 spaces on a single tab press.

2021-06-17 08:55 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.es
> +	const createIssueUrl = ({
Already done 🙋🏾  See 99dc85e14cdf415c265a22576fe0c5898b8dbb13

2021-06-17 08:57 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.es
> +		repoIssueUrl: `${rootDoc.data.repository}/issues`,
Because `repoUrl` when used previously is a parameter that is local to that function. However, I've got an idea that simplifies this. Hang on!

2021-06-17 08:58 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.html
> +		<article>
Indeed, the document does use spaces for indentation. However, the config files for both prettier and eslint specify that the code base should use tabs. So I converted the spaces in the code I touched to tabs. I'd be happy to change it back though, but in that case, we should also change the style configurations :shrug:

2021-06-17 09:02 UTC, poi33 commented on src/main/resources/site/parts/docpage/docpage.es
> +			formatted: moment(doc.modifedTime).format('LLL'),
Dates are personal and cant ever do it the way people prefer. I just go with iso formating since everyone has a different opinion on how it should look. (For me month before day is not logical). If this is really important, use moment on the frontend to get the local date from an iso string.

2021-06-17 09:04 UTC, poi33 commented on src/main/resources/site/parts/docpage/docpage.html
> +		<article>
Go ahead, we need to just set it to something and keep useing that.

2021-06-17 09:05 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.html
> +		<article>
Addressed in 838b3fe00ce731642197d766212b8b3c467038e5 (docpage.html) and 52353423e69dc48c15eee83e907da264226ebbae (docpage.es).

2021-06-17 09:05 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.es
> +		repoIssueUrl: `${rootDoc.data.repository}/issues`,
Fixed/changed in 52353423e69dc48c15eee83e907da264226ebbae

2021-06-17 09:09 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.es
> +			formatted: moment(doc.modifedTime).format('LLL'),
Addressed in cb2e0cdf7b1829fd1b92b118f62174e31ecb4b38, using the format specified above. I think using a more human-readable format is preferable for displaying dates and time, though I'm happy to discuss it.

2021-06-17 09:15 UTC, thomasheartman commented
> My suggestion: add a black border ontop of the feedback

You mean like a page break? Something like this? 

![image](https://user-images.githubusercontent.com/17786332/122368041-487d2000-cf5d-11eb-97f7-b0a4a3e0c9e2.png)

I think that's quite nice, actually.

2021-06-17 09:18 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.html
> +		<article>
Regarding changing the defaults; I'm not going to do it as part of this PR, but if the same style (spaces) is used throughout the rest of the project, then it's worth doing as a separate task, I think.

2021-06-17 09:28 UTC, thomasheartman commented on src/main/resources/site/parts/docpage/docpage.es
> +			formatted: moment(doc.modifedTime).format('LLL'),
Regarding what's the right format to use: does Enonic have a standard for this or is this personal preference? 

If we have a standard, I'd definitely follow that, of course. If it's up to the developer(s), then my vote goes to keeping the current format (April 5th, 2021), but we can discuss it if you feel strongly against it. My reasons are:

When it comes to displaying dates in a doc, I think readability and avoiding ambiguity are important. 

ISO (and variants, such as with spaces or slashes instead of hyphens) does this by clearly leading with the year, however I don't think it's as easy to parse (unless you're used to working with dates in ISO format). 

Using the long form ("April 5th, 2021") is also unambiguous and reads quite naturally. Could also use "5th of April, 2021", but I think I see that less often. 

Using dd/mm/yyyy or mm/dd/yyyy is problematic because they can easily get mixed up (is 4/10 April 10th or October 4th?).

2021-06-17 10:16 UTC, poi33 commented on src/main/resources/site/parts/docpage/docpage.es
> +			formatted: moment(doc.modifedTime).format('LLL'),
Just keep it as is. Dates starts a discussion everytime so i try to avaoid it since it never gets prefect.

2021-06-17 11:46 UTC, thomasheartman commented
Here's two fairly simple designs that I think could work. I'll put one of them up on QA fairly soon, and we can take it from there ☺️ 

![2021-06-17-134044_3474x626_scrot](https://user-images.githubusercontent.com/17786332/122390437-47a2b900-cf72-11eb-8183-f7df36873946.png)

2021-06-17 12:51 UTC, thomasheartman commented
Put the grey feedback box version up on QA now. @sigdestad Do you want to check it out? 

Personally, I think that it could still need some distinction. It blends a little into the guides now because code blocks use the same background color. Using both a block and a horizontal rule is a little better, though:

![image](https://user-images.githubusercontent.com/17786332/122393600-53dc4580-cf75-11eb-89a9-8eb3d28515be.png)

Optionally, we could also use a border with or without a horizontal rule. It could look something like this:

With:
![image](https://user-images.githubusercontent.com/17786332/122399732-5c377f00-cf7b-11eb-9749-b91eb42a4b22.png)

Without:

![image](https://user-images.githubusercontent.com/17786332/122399830-6eb1b880-cf7b-11eb-9ba4-3fc0584812d4.png)


Other ideas?

2021-06-17 13:22 UTC, thomasheartman commented
Another option is something like this:

![image](https://user-images.githubusercontent.com/17786332/122404710-bdf9e800-cf7f-11eb-9cf1-c38a512d32da.png)

It might require some link color tweaking to be legible and meet contrast requirements, but I like the basic idea 🙋🏾

2021-06-17 13:47 UTC, thomasheartman commented
Update to the above ☝🏾  I fixed the link color accessibility issues 😄 

![image](https://user-images.githubusercontent.com/17786332/122409286-50e85180-cf83-11eb-8b9f-ef299c11ffbd.png)

2021-06-17 15:15 UTC, sigdestad commented
Less is more :)

2021-06-18 09:34 UTC, thomasheartman commented
Got it! Something more like this, then?

![image](https://user-images.githubusercontent.com/17786332/122540683-28b32e00-d029-11eb-966e-0f584dbcb5e9.png)

2021-06-18 11:45 UTC, poi33 commented
I like how it looks now. Quite hidden, but stil easy to find if you are looking for it. 
Do the links open in a new tab? If so could you add the external page icon? (Used in the other sites of the menu)

2021-06-18 11:58 UTC, thomasheartman commented
No, the links don't open in a new page unless you ask them to. However, adding an external page icon might not be a bad idea anyway. Where do I find the icon? I tried looking around for it a bit. And if we want to add some indicator to external links, couldn't we use a css rule to do that automatically?

2021-06-18 12:00 UTC, poi33 commented on src/main/resources/assets/css/parts/_docpage.scss
> +.docpage-content__feedback-section {
This could be moved to .docpage-content grouping in the scss. 
Would be something like:
```
&-content {
   [...]
   &__feedback-section {
   }
}
```
Section is a html element so <section class="docpage-content__feedback-section" is kind of double up?

2021-06-18 12:17 UTC, thomasheartman commented on src/main/resources/assets/css/parts/_docpage.scss
> +.docpage-content__feedback-section {
Yeah, that's a good point. I tried but didn't get it to register, so I moved it to the top level to make sure it'd work. I'll move it back in. And it's not actually a `section` element right now. It's just an unordered list `ul`. I'm not actually sure whether it needs a wrapper or not. If it does, `section` may be a good choice, but so might `aside`. 🤔 

The [MDN docs on section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) say this:
> If the contents represent useful tangential information that works alongside the main content, but is not directly part of it (like related links, or an author bio), use an <aside>.

2021-06-18 12:57 UTC, poi33 commented
> Where do I find the icon? 
Its on master now. Added the pull request. So if you rebase this with master it should show up in the asset icon

> And if we want to add some indicator to external links, couldn't we use a css rule to do that automatically?
Yeah make scss mixin that adds an ::after with the icon would do wonders. 
Should allready do something close to that in the menu: 
Yeah just reuse the external icon from here:
```
      .external {
        display: inline-block;
        width: 15px;
        height: 15px;
        color: $color-black;
        background-image: url("../img/external-page.svg");
      }
```

2021-06-18 13:27 UTC, sigdestad commented
Nice!

2021-06-18 13:46 UTC, thomasheartman commented
@poi33 Sweet! I ran into some problems when merging master now (master doesn't build for me), but I'll have a look at it on Monday. I think it's due to the updated Node versions etc.


And for the external icons, I was thinking of doing something more general than a Sass mixin. Something like this rule:

```css
article a[href^="http://"]::after,
article a[href^="https://"]::after {
  background-image: url("../img/external-page.svg");
}
```

Optionally with a `:not([href*="mysite.com"])`  after if we don't want it to apply to absolute links to the same domain. We could potentially save a lot of work if that works. What do you think? Is it doable? I don't really know how most links on that site work, so it might not be feasible.

2021-06-21 06:48 UTC, thomasheartman commented
@poi33 I've got some ideas on link styling for external links that I'd like to run by you. However, it feels like an issue that's not directly related to the feedback section. I'm thinking it might be worth making it a separate task / issue and instead get this merged and up and running. What do you think?

2021-06-21 09:06 UTC, poi33 approved these changes

2021-06-21 09:07 UTC, merged