New part: "market-latest"
enonic/site-developer pull request #656
Opened 2022-02-18 18:43 UTC by reisfmb

2022-02-21 15:53 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +        const marketLatestDiv = document.getElementsByClassName('market_latest')[0];
document.querySelector('.market_latest'); is easier to understand. Functinally the same.

2022-02-21 15:55 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +        const graphqlQuery = marketLatestDiv.getAttribute('data-graphqlQuery');
data attributes are easier to get. No need to get the attribute. 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

2022-02-21 15:57 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +const _post = async (url, body) => {
Put all function inside the dom event listner. 
Then they will not be globally scoped. 
Eg. if you use _post in some other file on the side. It will not override the `_post` name

2022-02-21 15:59 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +    marketLatestDiv.innerHTML = `<p>No items to show.</p>`;
Don't use innerHtml. If possible, never ever. 
Create a new P element. And add text to it. 
`document.createElement('p')` and `p.textContent = 'No items to show'`

2022-02-21 16:01 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +        cardDiv.setAttribute('class', 'market_latest__card');
A bit of a wierd way to set class. I usually see: 
`cardDiv.className.append()` ?

2022-02-21 16:04 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +        cardDescriptionDivP1.innerText = item.shortDescription;
innerText is not really used anymore. Could we change it to textContent?

2022-02-21 16:13 UTC, poi33 commented on src/main/resources/lib/globalCache.es
> +app.cache = app.cache || {};
Assigning a global value on the app namespace 😓  
`const  cache = {}` should work be fine. I think the lib code is only executed once when the server loads. (or fist time its accessed from a controller or simular) 
Then we can modify the object anyway we want after that.

2022-02-21 16:21 UTC, poi33 commented on src/main/resources/lib/globalCache.es
> +    if (!options || options.toString() !== '[object Object]') {
This is a strange way to check for object type. 
`TypeOf` ?

2022-02-21 16:22 UTC, poi33 commented on src/main/resources/lib/globalCache.es
> +        minimumSize = 1,
I think this will be var minimumSize if initialized like this. Do you know?

2022-02-21 16:25 UTC, poi33 commented on src/main/resources/services/market/market.es
> +const CACHE_NAME = `${app.name}:market-latest`;
Why the app name here?

2022-02-21 16:25 UTC, poi33 commented on src/main/resources/services/market/market.es
> +    const _getIconIconUrl = (item) => {
Icon twice in the name?

2022-02-21 16:27 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +        .replace(/(\r\n|\r|  |)/gm, "")
The query does not work with newlines?

2022-02-21 16:35 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.html
> +<div th:if="${hasCachedItems}" class="market_latest">
Such a tiny html file with so much server code. 😄

2022-02-21 19:09 UTC, reisfmb commented on src/main/resources/assets/js/parts/market-latest.es
> +const _post = async (url, body) => {
Nice one Persijn, thank you :)

2022-02-21 19:57 UTC, reisfmb commented on src/main/resources/lib/globalCache.es
> +    if (!options || options.toString() !== '[object Object]') {
Here are some problems with `typeof`:

![image](https://user-images.githubusercontent.com/67838246/155018907-448ffa98-b855-4052-9f6c-14667457f2fd.png)

A nice article discussing that: [https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/](https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/)

2022-02-21 20:00 UTC, reisfmb commented on src/main/resources/assets/js/parts/market-latest.es
> +        cardDiv.setAttribute('class', 'market_latest__card');
I believe that you meant `.classList.add()` right? Changed to that!

2022-02-21 20:04 UTC, reisfmb commented on src/main/resources/lib/globalCache.es
> +        minimumSize = 1,
From what I've checked, those declarations will be constants. Why do you think that they'll be `var` if initialized like that?

2022-02-21 20:06 UTC, reisfmb commented on src/main/resources/site/parts/market-latest/market-latest.es
> +        .replace(/(\r\n|\r|  |)/gm, "")
It actually works, I only did that to make the custom data attribute more clean inside the DOM: :grinning: 

without `.replace(/(\r\n|\r|  |)/gm, "")`:

![image](https://user-images.githubusercontent.com/67838246/155019871-56325773-262a-4d9f-be03-123d059df20d.png)


with `.replace(/(\r\n|\r|  |)/gm, "")`:

![image](https://user-images.githubusercontent.com/67838246/155017810-f2a8b876-2ead-4771-957f-eabbe11feefd.png)

2022-02-21 20:07 UTC, reisfmb commented on src/main/resources/services/market/market.es
> +const CACHE_NAME = `${app.name}:market-latest`;
Haven't though much about that... I agree that there's no need to use `app.name`. Changed to `cache:market-latest`.

2022-02-21 20:15 UTC, reisfmb commented on src/main/resources/lib/globalCache.es
> +app.cache = app.cache || {};
I tried without using cache globally, but the problem is that I need to use the same cache in two different places: in the part controller (initialization with lib-cache) and also in the service (to set the cache with the properly formatted data). This is the reason that I went globally with the cache and implemented a super simple global cache lib

2022-02-22 09:42 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +        cardDiv.setAttribute('class', 'market_latest__card');
🙈 Yes, className is react i think.... classList is what i meant. I see you catch on to my suggestions even if I'm wrong 😆

2022-02-22 10:09 UTC, poi33 commented on src/main/resources/lib/globalCache.es
> +app.cache = app.cache || {};
As long as the service and the part controller call the same lib, they should access the same object. (cluster servers make this a little more complex). 
If you define const allCaches = {} and set all caches inside the object. You should get the same global behavior without accessing the app namespace

2022-02-22 10:10 UTC, poi33 commented on src/main/resources/lib/globalCache.es
> +        minimumSize = 1,
Looked this up, if you forget the comma eg:
`const minimumNameLen = 1
minimumSize = 1, ` 
Then this will be globally scoped. 
I never use this initialization myself.

2022-02-22 10:12 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +        .replace(/(\r\n|\r|  |)/gm, "")
I see, did not think about the dom element attr 👍

2022-02-22 12:14 UTC, poi33 requested changes

2022-02-23 09:42 UTC, poi33 requested changes
Getting access to another site on the server is quite difficult 😣

2022-02-23 09:42 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +            const marketSite = getSite({ key: '/enonic-market' });
lib-content - [getSite](https://developer.enonic.com/docs/xp/stable/api/lib-content#getsite): 'This function returns the parent site of a content' 
I have no idea what it will return if you pass in a site itself into this function.

2022-02-23 09:42 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +            const marketSite = getSite({ key: '/enonic-market' });
If the context is set properly then portal.getSite() should do the trick. 
If it still complains we can do it the brute force way: [connect](https://developer.enonic.com/docs/xp/stable/api/lib-node#connect) to the repo. [get](https://developer.enonic.com/docs/xp/stable/api/lib-node#get) the nodeid. Force it into a portal.pageUrl();

If all this fails we just put the market link in the app config, or app config file.

2022-02-23 09:42 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +const CONTEXT_SETTINGS = { repository: 'com.enonic.cms.market' };
The RunContext probably needs some principal to run properly? Not sure, could you try adding `principals: ["role:system.admin"]`.

2022-02-23 20:23 UTC, reisfmb commented on src/main/resources/lib/globalCache.es
> +app.cache = app.cache || {};
With the new approach (using only part controller + client script) we'll not need a global cache. Removed it in the latest commit.

2022-02-23 20:25 UTC, reisfmb commented on src/main/resources/site/parts/market-latest/market-latest.es
> +            const marketSite = getSite({ key: '/enonic-market' });
Since we're hardcoding the URL to be the one from market, I can't use context and look at things locally anymore, so I've removed the `adjustProjectUrl` function and now the code related to get the icon and the url are harcoded. We'll probably need to adjust this later on:

```
const _formatMarketItems = (marketUrl, rawMarketItems) => {
    const _getIconUrl = (item) => {
        const name = item.data.icon || item.data.iconAttachment.name;
        return `${marketUrl}/_/attachment/inline/${item._id}/${name}`
    }

    const items = rawMarketItems
        .map((item) => ({
            name: item.displayName,
            shortDescription: item.data.shortDescription,
            url: `${marketUrl}${item.pageUrl}`,
            icon: _getIconUrl(item),
            readableTimeDifference: getReadableTimeDifference(item.modifiedTime)
        }));

    return items;
}
```

2022-02-23 20:31 UTC, reisfmb commented
@poi33 one thing that I also take a look at was the case if the same part was added with multiplicity on a page.

This was not working before since we were using `document.querySelector`... now the client script uses `document.getElementsByClassName('market_latest')` and executes the code for each of them. 

I also noticed that adding multiple parts does not imply rendering with multiplicity the same client script (which is good in this case). Do you know why? Is this something that the `pageContributtions` take care of?

If possible, call me on slack for us to discuss if this will be needed or not :)

2022-02-23 23:29 UTC, sigdestad commented
Bruno. Guillotine has a field that will give you a URL to the attachment directly, No need to generate this in the client (dev portal code)

2022-02-23 23:29 UTC, sigdestad commented
@anatol-sialitski can show you this

2022-02-23 23:31 UTC, sigdestad commented
Also, just use the component path as unique identifier to separate multiple instances of a part

2022-02-24 08:56 UTC, anatol-sialitski commented
@reisfmb please have a look at
![image](https://user-images.githubusercontent.com/53557255/155491510-52aaa001-ec6e-4006-9da7-27428e03e7c0.png)

2022-02-24 11:57 UTC, reisfmb commented
> Bruno. Guillotine has a field that will give you a URL to the attachment directly, No need to generate this in the client (dev portal code)

@anatol-sialitski 

I know about that, the problem is that this is not available for on `com_enonic_app_market_Application` since icon in this case is a string (why ?), that's why I preferred to go that other way for all of them.

![image](https://user-images.githubusercontent.com/67838246/155519497-f2aa80c5-8e93-4ec9-a12c-5a4cf5fa23bd.png)

2022-02-24 12:50 UTC, poi33 requested changes

2022-02-24 12:50 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +const CACHE = newCache({ size: 1, expire: 3600 });
ALL_CAPS_VARIABLES should only be used on permanent variables. 
Variables that will never change and shuould not change. 
```suggestion
const cache = newCache({ size: 1, expire: 3600 });
```

2022-02-24 12:50 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +    const PART_URL = componentUrl();
The value is retrieved from a function. So it is not a permanent value. 
If the part is placed in different places this variable will be different.
```suggestion
    const part_url = componentUrl();
```

2022-02-24 13:55 UTC, reisfmb commented on src/main/resources/assets/js/parts/market-latest.es
> +    const _getInnerHTMLfromHTMLstring = (s) => s.replace(/(?:^<div[^>]*>)|(?:<\/div>$)/g, "");
Yep, I'm stripping away the outer div element from the injected HTML. 

We might need to do that somehow because we're injecting the HTML in the div with class "market_latest", and the HTML that we're injecting is the full HTML generated by thyemleaf from the HTML of the part. If we don't do that, the injected HTML would be something like:

```HTML
<div class="market_latest">
   <div class="market_latest">...</div> // this is the injected HTML
</div>
```

2022-02-24 14:00 UTC, reisfmb commented on src/main/resources/site/parts/market-latest/market-latest.es
> +            url: `${marketUrl}${item.pageUrl}`,
Can you be more specific here please?

2022-02-24 14:58 UTC, poi33 requested changes

2022-02-24 14:58 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +    const _getInnerHTMLfromHTMLstring = (s) => s.replace(/(?:^<div[^>]*>)|(?:<\/div>$)/g, "");
Ok i see you use the same viewfile in both. We can simply strip away the top level stuff with thymeleaf.

2022-02-24 14:58 UTC, poi33 commented on src/main/resources/assets/js/parts/market-latest.es
> +    const _getInnerHTMLfromHTMLstring = (s) => s.replace(/(?:^<div[^>]*>)|(?:<\/div>$)/g, "");
Ok i see you use the same viewfile in both. We can simply strip away the top level stuff with thymeleaf.

2022-02-24 14:58 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.html
> +<div th:if="${hasCachedItems}" class="market_latest">
Do a conditional remove tag if we don't want to render the topLevel div. 
Just add it to the modal when rendering the output.
```suggestion
<div th:if="${hasCachedItems}" th:remove="${removeTop ? 'tag' : ''}" class="market_latest">
```

2022-02-24 15:04 UTC, reisfmb commented on src/main/resources/site/parts/market-latest/market-latest.html
> +<div th:if="${hasCachedItems}" class="market_latest">
Such a nice approach! Thank you Persijn, I'll do that :)

2022-02-24 16:29 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +    if (HEADERS_ACCEPT.indexOf('application/json') >= 0) {
I know practically impossible. But we only want one of them to run. So the code should tell us the same?

2022-02-24 17:01 UTC, poi33 commented on src/main/resources/site/parts/market-latest/market-latest.es
> +            url: `${marketUrl}${item.pageUrl}`,
https://github.com/enonic/lib-guillotine/blob/master/docs/api.adoc#fields-2 `pageUrl` to get the correct page? Or is this not possible?

2022-02-24 17:38 UTC, sigdestad commented
@reisfmb - In regards to the attachment string issue, I believe this will be automatically fixed when we upgrade the Guilllotine library tomorrow!

2022-02-24 18:10 UTC, reisfmb commented
@sigdestad Perfect Thomas, if that is the case, then I'll update the query accordingly :)

2022-02-24 23:23 UTC, sigdestad commented
Field sets are purely UI, so they should not matter when generating schema. Fieldset used to have a name attributt back in the Days.

2022-02-24 23:24 UTC, sigdestad commented
Field sets are purely UI, so they should not matter when generating schema. Fieldset used to have a name back in the Days.

2022-02-25 09:07 UTC, anatol-sialitski commented
Ok. Then that should be done here https://github.com/enonic/site-market/blob/0651f1a700a30578bd0e092c75d2cbc81a262c3d/src/main/resources/lib/enonic/graphql/index.js#L84
```
'com_enonic_app_market_Application_Data': function (context, params) {
            params.fields.icon = {
                type: graphQlLib.reference('Attachment')
            }
        }
```

2022-03-01 17:04 UTC, merged