New stats part
enonic/site-developer pull request #666
Opened 2022-02-25 12:29 UTC by poi33

Shows a activity graph
Releases done by enonic the last year

2022-02-25 14:38 UTC, reisfmb commented on src/main/resources/assets/js/parts/stats-front.es
> +    const timeoutId = setTimeout(() => controller.abort(), 1000);
Where are you currently using `timeoutId` ?

2022-02-25 14:39 UTC, reisfmb commented on src/main/resources/assets/js/parts/stats-front.es
> +     * Async method for getting the grpah data
grpah -> graph

2022-02-25 14:39 UTC, reisfmb commented on src/main/resources/assets/js/parts/stats-front.es
> +     * Creates an svg grpah of the given line data
grpah -> graph

2022-02-25 14:40 UTC, reisfmb commented on src/main/resources/assets/js/parts/stats-front.es
> +    // Add loading icon to part
For the loading I suggest the use of that loading dots (_dots.scss file) we are using in the news / market-latest parts.

2022-02-25 14:42 UTC, reisfmb requested changes
For me, everything seems good so far... I added few comments with some improvements suggestions. Feel free to ignore them :+1:

2022-02-25 14:46 UTC, poi33 commented on src/main/resources/site/parts/stats/stats.es
> +    if (headerAccept.indexOf('application/json') >= 0) {
I like this seperation. The current seperation i have is each http call is its own object. So its possible to try catch it.
But I see the benefit of adding the github api calls to one dataset combined.

2022-02-25 14:48 UTC, poi33 commented on src/main/resources/assets/js/parts/stats-front.es
> +    const timeoutId = setTimeout(() => controller.abort(), 1000);
Timeoutid is not used. You usually need the refrence to clear timeouts.

2022-02-25 14:48 UTC, poi33 commented on src/main/resources/assets/js/parts/stats-front.es
> +    // Add loading icon to part
Yeah, but i need your code to add it 😄 Was waiting for it to get merged into master

2022-03-02 08:53 UTC, poi33 commented on src/main/resources/assets/css/parts/_stats.scss
> +		@for $i from 1 through 6 {
@reisfmb why did you remove my comments? This scss magic is not understandable for everyone.

2022-03-02 08:57 UTC, poi33 commented on src/main/resources/site/site.xml
> +<site xmlns="urn:enonic:xp:model:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:enonic:xp:model:1.0 https://raw.githubusercontent.com/enonic/xp/master/modules/core
This is not readable. 
It needs to be on seperate lines @reisfmb

2022-03-02 15:51 UTC, poi33 commented on src/main/resources/assets/js/parts/stats-front.es
> +                part.classList.remove('flex-center');
classList remove and add not suported by ie11 😄 https://caniuse.com/classlist
Soooo do we want to support it?

2022-03-02 16:04 UTC, reisfmb commented on src/main/resources/site/parts/stats/stats.es
> +    return render(releaseView, model);
Because `sanitizeHTML` was removing the custom data-* attributes used to set animations properties in the `.num` class

2022-03-02 16:06 UTC, reisfmb commented on src/main/resources/assets/css/parts/_stats.scss
> -				// Chose the start end corresponding to the grid above
I don't remember, I'll add them again :)

2022-03-02 16:11 UTC, reisfmb commented on src/main/resources/assets/js/parts/stats-front.es
> +                part.classList.remove('flex-center');
I guess this is good to have support, because if we don't remove the `flex-center` class, things will be visually incorrect. I can change it to `document.querySelector('.part-stats__data').className = 'part-stats__data';`. Do you agree on that?

2022-03-03 09:27 UTC, poi33 reviewed
Looks good 👍

2022-03-03 15:03 UTC, reisfmb commented on src/main/resources/site/parts/stats/stats.es
> +    expire: 30 //60 * 60 // 60 sec * 60 min = 1 hour
It was my bad, I changed it to test locally and forget to go back to 1 hour. Fixed that in [this commit](https://github.com/enonic/site-developer/pull/666/commits/2a10727862b95094c52e9261c950045b84d1a213)

2022-03-07 16:40 UTC, reisfmb approved these changes

2022-03-08 09:12 UTC, merged